.Dd 8/20/2023               \" DATE
.Dt TMUX-RENAME-PANE 1      \" Program name and manual section number
.Os Unix-like
.Sh NAME                 \" Section Header - required - don't modify
.Nd tmux-rename-pane - Renames custom title of active tmux pane.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Ar title              \" [title]
.Sh DESCRIPTION          \" Section Header - required - don't modify
Renames the custom title of th current pane in an active tmux session.
If the
.Ar title
is not provided, the custom tile of the pane will be cleared.
