.Dd 8/20/2023               \" DATE
.Dt TMUX-DISABLE-PANE-TITLES 1      \" Program name and manual section number
.Os Unix-like
.Sh NAME                 \" Section Header - required - don't modify
.Nd tmux-disable-pane-titles - Enables pane titles in current window
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Sh DESCRIPTION          \" Section Header - required - don't modify
Disables the title of the panes in the current tmux session's window.
