if [[ "$PATH" != *"$HOME/.local/bin"* ]]; then
        export PATH="$PATH:$HOME/.local/bin"
fi

function add_wezterm_to_path_macos {
	WEZTERM_ROOT_PATH=/Applications/WezTerm.app
	if [[ -d "$WEZTERM_ROOT_PATH" && "$PATH" != *"$WEZTERM_ROOT_PATH"* ]]
	then
		export PATH="$PATH:$WEZTERM_ROOT_PATH/Contents/MacOS"
	fi
}

# MacOS ncurses version is old and does not contain the terminfo used by
# tmux. This function makes sure that the terminfo for tmux is present,
# assuming we have added it. For more info, look at
# https://gpanders.com/blog/the-definitive-guide-to-using-tmux-256color-on-macos/
function add_tmux_terminfo_macos {
	CUSTOM_TERMINFO="$HOME/.local/share/terminfo"
	if [[ -d "$CUSTOM_TERMINFO" ]]; then
		export TERMINFO_DIRS="$TERMINFO_DIRS:$CUSTOM_TERMINFO"
	fi
}

# Specify configurations specific to Linux
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
	:
# Specify configurations specific to MacOs
elif [[ "$OSTYPE" == "darwin"* ]] then
	add_wezterm_to_path_macos
	add_tmux_terminfo_macos
# Unknown OS
else
	echo "Unknown OS. Your ZSH configuration might not work properly."
fi
